import type { Metadata } from "next";
import "react-toastify/dist/ReactToastify.css";

import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Maubay Crops",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
